# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: build packages

"on":
  push:
    branches:
      - master

jobs:
  build:
    # runs-on: [self-hosted, Linux, X64]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        release: [edge]  # TODO 3.12, 3.11, etc

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
          clean: false
      - uses: actions/cache@v4
        with:
          path: |
            apkcache/
            distfiles/
            .ccache/
          # packages/
          key: ${{ matrix.release }}
      - name: make build
        run: |
          # pwd ; find * ; env
          mkdir -p apkcache/ distfiles/ packages/ .ccache/ .abuild/
          rm -f packages/${{ matrix.release }}/main/x86_64/*.apk
          sudo chown -R 1000:1000 .
          make build
        env:
          RELEASE: ${{ matrix.release }}
          PACKAGER: ${{ secrets.PACKAGER }}
          PACKAGER_PRIVKEY: ${{ secrets.PACKAGER_PRIVKEY }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          JOBS: ${{ secrets.JOBS }}
          REPODEST: /home/build/packages/${{ matrix.release }}
      # if we are merging into the master branch, upload the built package
      - if: github.ref == 'refs/heads/master'
        name: upload packages
        run: |
          set -x
          cd packages/${{ matrix.release }}/main/x86_64
          for apk in $(find . -type f -name '*.apk') ; do
            echo "Uploading $apk to packages.atlascloud.xyz"
            curl -sSL \
              -H 'Authorization: Bearer ${{ secrets.PACKAGES_TOKEN }}' \
              -F "architecture=x86_64;type=text/plain" \
              -F "package=@${apk}" \
              https://packages.atlascloud.xyz/api/atlascloud/alpine/${{ matrix.release }}/main/x86_64/pkgs
          done
